# Generated by precisionFDA exporter (v1.0.3) on 2018-06-14 06:02:56 +0000
# The asset download links in this file are valid only for 24h.

# Exported app: demosj, revision: 4, authored by: justin.shang
# https://precision.fda.gov/apps/app-F07pGv80p37Pqvj8VxzZZ3jv

# For more information please consult the app export section in the precisionFDA docs

# Start with Ubuntu 14.04 base image
FROM ubuntu:14.04

# Install default precisionFDA Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	aria2 \
	byobu \
	cmake \
	cpanminus \
	curl \
	dstat \
	g++ \
	git \
	htop \
	libboost-all-dev \
	libcurl4-openssl-dev \
	libncurses5-dev \
	make \
	perl \
	pypy \
	python-dev \
	python-pip \
	r-base \
	ruby1.9.3 \
	wget \
	xz-utils

# Install default precisionFDA python packages
RUN pip install \
	requests==2.5.0 \
	futures==2.2.0 \
	setuptools==10.2

# Add DNAnexus repo to apt-get
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/' > /etc/apt/sources.list.d/dnanexus.list"
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/' >> /etc/apt/sources.list.d/dnanexus.list"
RUN curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add -

# Install app-specific Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	plink \
	vcftools

# Download helper executables
RUN curl https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions

# Write app spec and code to root folder
RUN ["/bin/bash","-c","echo -E \\{\\\"spec\\\":\\{\\\"input_spec\\\":\\[\\{\\\"name\\\":\\\"vcf\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"VCF\\ Input\\ File\\\",\\\"help\\\":\\\"Crystal_Genetics_Cancer_Panel_V1.0_NA12878.vcf\\\"\\},\\{\\\"name\\\":\\\"chromosome\\\",\\\"class\\\":\\\"string\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Chromosome\\\",\\\"help\\\":\\\"Chromosome\\\",\\\"default\\\":\\\"2\\\"\\},\\{\\\"name\\\":\\\"start\\\",\\\"class\\\":\\\"int\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Start\\ Position\\\",\\\"help\\\":\\\"Start\\ Position\\\",\\\"default\\\":47602241\\},\\{\\\"name\\\":\\\"end\\\",\\\"class\\\":\\\"int\\\",\\\"optional\\\":false,\\\"label\\\":\\\"End\\ Position\\\",\\\"help\\\":\\\"End\\ Position\\\",\\\"default\\\":47640088\\}\\],\\\"output_spec\\\":\\[\\{\\\"name\\\":\\\"output\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Per-Sample\\ Missingness\\\",\\\"help\\\":\\\"Per-Sample\\ Missingness\\\"\\}\\],\\\"internet_access\\\":false,\\\"instance_type\\\":\\\"baseline-8\\\"\\},\\\"assets\\\":\\[\\],\\\"packages\\\":\\[\\\"plink\\\",\\\"vcftools\\\"\\]\\} \u003e /spec.json"]
RUN ["/bin/bash","-c","echo -E \\{\\\"code\\\":\\\"\\#\\ Ensure\\ piped\\ commands\\ do\\ not\\ fail\\ based\\ on\\ built-in\\ non-zero\\ return\\ codes\\\\nset\\ \\+o\\ pipefail\\\\n\\\\n\\#\\ Extract\\ data\\ for\\ a\\ range\\ using\\ VCFTools\\ and\\ convert\\ to\\ PLINK\\ format\\\\nvcftools\\ --gzvcf\\ \\$vcf_path\\ --chr\\ \\$chromosome\\ --from-bp\\ \\$start\\ --to-bp\\ \\$end\\ --out\\ filtered\\ --plink\\\\n\\\\n\\#\\ Run\\ PLINK\\ MISSING\\ to\\ calculate\\ per-sample\\ missingness\\\\np-link\\ --file\\ filtered\\ --out\\ filtered\\ --missing\\\\n\\\\n\\#\\ Emit\\ the\\ INDIVIDUAL\\ MISSINGNESS\\ \\(.imiss\\)\\ file\\ as\\ the\\ \\\\\\\"output\\\\\\\"\\ parameter\\\\nemit\\ output\\ filtered.imiss\\\\n\\\"\\} | python -c 'import sys,json; print json.load(sys.stdin)[\"code\"]' \u003e /script.sh"]

# Create directory /work and set it to $HOME and CWD
RUN mkdir -p /work
ENV HOME="/work"
WORKDIR /work

# Set entry point to container
ENTRYPOINT ["/usr/bin/run"]

VOLUME /data
VOLUME /work